export const copy = {
  ar: {
    nav: [
      ["الرئيسية", "/"],
      ["حكايتنا", "/about"],
      ["المنيو", "/menu"],
      ["الفروع", "/branches"],
      ["التقييمات", "/reviews"],
    ],
    call: "اطلب دلوقتي",
    heroEyebrow: "كشري أبو طارك — من قلب القاهرة",
    heroTitleA: "كشري",
    heroTitleB: "أبو طارك",
    heroText: "أرز، عدس، مكرونة، صلصة ودقة. مكونات بسيطة صنعت أشهر طبق كشري في مصر.",
    menuCta: "شوف المنيو",
    callCta: "التقييمات",
    stats: ["فروع", "متابع", "بيوصّوا بنا", "مراجعة"],
    featureEyebrow: "من أول طبق لآخر لقمة",
    featureTitle: "الحكاية كلها في الطعم",
    features: [
      ["كشري أصلي", "نفس الطبقات والنكهات من سنة 1950."],
      ["مكونات طازجة", "أرز وعدس ومكرونة كل يوم."],
      ["صلصة ودقة", "طماطم غنية وخل وثوم وكمون."],
      ["بصل مقرمش", "اللمسة الأخيرة والأشهر."],
    ],
    aboutEyebrow: "حكايتنا",
    aboutTitle: "من قلب وسط البلد لكل مصر",
    aboutP1: "بدأنا بطبق كشري بسيط في وسط البلد. الطعم الصح والناس اللي رجعت تاني وترغي خلتنا نكبر.",
    aboutP2: "النهارده، كشري أبو طارك بيخدم آلاف العائلات من كل مكان، بنفس الطبقات ونفس الطعم اللي الناس حبتة.",
    aboutPoints: ["أرز وعدس ومكرونة أصلية", "صلصة طماطم يومية", "بصل مقرمش طازج", "دقةخل وثوم وكمون"],
    visit: "اختار أقرب فرع",
    menuEyebrow: "المنيو",
    menuTitle: "أصناف كشري أبو طارك",
    menuNote: "الأسعار الحالية استرشادية لحين اعتماد المنيو الرسمي. اتصل بالفرع لتأكيد السعر والتوافر.",
    popular: "الأكثر طلبًا",
    spicy: "حار",
    currency: "ج.م",
    galleryEyebrow: "من المطبخ",
    galleryTitle: "الطبق اللي مستنيك",
    reviewsEyebrow: "رأي الناس",
    reviewsTitle: "ثقة مبنية على تقييمات حقيقية",
    reviewsText: "تقييمات ناس دقت كشري أبو طارك وحبتة.",
    facebookReviews: "شوف تقييمات فيسبوك",
    reviewsLabels: ["بيوصّوا بأبو طارك", "تقييم على فيسبوك", "متابع للصفحة"],
    reviewForm: {
      title: "كتب تجربتك",
      subtitle: "اسمك وتقييمك هيتشاركا بعد المراجعة.",
      nameLabel: "الاسم",
      namePlaceholder: "اسمك هنا",
      ratingLabel: "التقييم",
      branchLabel: "الفرع (اختياري)",
      branchPlaceholder: "اختار فرع",
      textLabel: "تجربتك",
      textPlaceholder: "قولنا عن أكلك وتجربتك...",
      submit: "ابعت التقييم",
      submitting: "جاري الإرسال...",
      successTitle: "شكراً!",
      successText: "تقييمك اتبعت وهيظهر بعد المراجعة.",
    },
    branchesEyebrow: "فروعنا",
    branchesTitle: "أبو طارك أقرب مما تتخيل",
    directions: "الاتجاهات",
    whatsapp: "واتساب",
    footerText: "كشري أبو طارك — من قلب القاهرة منذ 1950. طبقات بسيطة، طعم مش بيتنسي.",
    quickLinks: "روابط سريعة",
    hours: "مواعيد العمل",
    hoursValue: "اتصل بالفرع لتأكيد مواعيد العمل",
    follow: "تابعنا على فيسبوك",
    rights: "جميع الحقوق محفوظة لكشري أبو طارك",
    loading: "كشري أبو طارك",
  },
  en: {
    nav: [
      ["Home", "/"],
      ["Our Story", "/about"],
      ["Menu", "/menu"],
      ["Branches", "/branches"],
      ["Reviews", "/reviews"],
    ],
    call: "Order now",
    heroEyebrow: "Abo Tarek Koshari — From the heart of Cairo",
    heroTitleA: "Abo Tarek",
    heroTitleB: "Koshari",
    heroText: "Rice, lentils, pasta, tomato sauce and daqqa. Simple ingredients that made Egypt's most famous koshari.",
    menuCta: "Explore the menu",
    callCta: "Reviews",
    stats: ["Branches", "Followers", "Recommend us", "Reviews"],
    featureEyebrow: "From the first bowl to the last bite",
    featureTitle: "The whole story is in the flavour",
    features: [
      ["Authentic koshari", "The same layers and flavours since 1950."],
      ["Fresh ingredients", "Rice, lentils and pasta, every day."],
      ["Sauce & daqqa", "Rich tomato, vinegar, garlic and cumin."],
      ["Crispy onions", "The final and iconic touch."],
    ],
    aboutEyebrow: "Our story",
    aboutTitle: "From Downtown Cairo to all of Egypt",
    aboutP1: "We started with a simple bowl of koshari in Downtown Cairo. The right taste and people who kept coming back helped us grow.",
    aboutP2: "Today, Abo Tarek Koshari serves thousands of families from everywhere, with the same layers and the same taste people loved.",
    aboutPoints: ["Authentic rice, lentils & pasta", "Fresh daily tomato sauce", "Crispy golden onions", "Vinegar, garlic & cumin daqqa"],
    visit: "Find your nearest branch",
    menuEyebrow: "The Menu",
    menuTitle: "Abo Tarek Koshari Menu",
    menuNote: "Current prices are indicative until the official menu is approved. Call a branch to confirm price and availability.",
    popular: "Most ordered",
    spicy: "Spicy",
    currency: "EGP",
    galleryEyebrow: "From the kitchen",
    galleryTitle: "The bowl that's waiting for you",
    reviewsEyebrow: "Customer confidence",
    reviewsTitle: "Trust backed by real reviews",
    reviewsText: "Reviews from people who tried Abo Tarek Koshari and loved it.",
    facebookReviews: "View Facebook reviews",
    reviewsLabels: ["Recommend Abo Tarek", "Facebook reviews", "Page followers"],
    reviewForm: {
      title: "Share your experience",
      subtitle: "Your name and rating will be posted after review.",
      nameLabel: "Name",
      namePlaceholder: "Your name",
      ratingLabel: "Rating",
      branchLabel: "Branch (optional)",
      branchPlaceholder: "Select a branch",
      textLabel: "Your review",
      textPlaceholder: "Tell us about your meal and experience...",
      submit: "Submit review",
      submitting: "Submitting...",
      successTitle: "Thank you!",
      successText: "Your review has been submitted and will appear after approval.",
    },
    branchesEyebrow: "Our branches",
    branchesTitle: "Abo Tarek is closer than you think",
    directions: "Directions",
    whatsapp: "WhatsApp",
    footerText: "Abo Tarek Koshari — from the heart of Cairo since 1950. Simple layers, unforgettable taste.",
    quickLinks: "Quick links",
    hours: "Opening hours",
    hoursValue: "Call the branch to confirm opening hours",
    follow: "Follow us on Facebook",
    rights: "All rights reserved to Abo Tarek Koshari",
    loading: "Abo Tarek Koshari",
  },
} as const;
